version: '3.8'

services:
  photo_portrait_bot:
    build: .
    container_name: photo_portrait_bot
    depends_on:
      - redis
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    networks:
      - bot_network
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./static:/app/static

  redis:
    image: redis:7-alpine
    container_name: photo_portrait_bot_redis
    restart: unless-stopped
    networks:
      - bot_network
    ports:
      - "127.0.0.1:6379:6379"

networks:
  bot_network:
    driver: bridge